import targetClean from '../../assets/Target_Clean.png'
import targetZero from '../../assets/Target_Zero.png'
import Circular from '../../assets/CircularByDesign.png'

export const ENTERPRISE_PRIORITIES = {
  LTO: [
    {
      id: 1,
      key: "01",
      width: 82,
      left: 38,
      top: 10,
      color: "#0c4a6e",
      label: "Hilton Carter",
      description01: "• Hilton Carter (Project Flower)",
      description02: "• Product Category: Home/Outdoor",
    },
    {
      id: 2,
      key: "02",
      width: 82,
      left: 123,
      top: 10,
      color: "#0c4a6e",
      label: "Project Diamond",
      description01: "• Product Category: A&A -  Women's & Girls",
      description02: "• Tied to Women's History Month",
    },
    {
      id: 3,
      key: "03",
      width: 83,
      left: 631,
      top: 10,
      color: "#0c4a6e",
      label: "Project Unity",
      description01: "• Product Categories: Pets and Apparel",
    },
  ],

  // ===================== TGT FORWARD

  ALWAYS: [
    {
      id: 1,
      key: "01",
      width: 1000,
      left: 40,
      top: 5,
      color: "#0891b2",
      image: targetClean,
      label: "Target Clean",
      description01: "Target Clean is a program that helps guests find products that are formulated without ingredients they may not want and - in applicable categories - are cruelty-free ",
      description02: "Learn more about Target Clean",
      description03: "https://www.target.com/c/target-clean/-/N-p4n12",
    },
    {
      id: 2,
      key: "02",
      width: 1000,
      left: 40,
      top: 55,
      color: "#0891b2",
      image: targetZero,
      label: "Target Zero",
      description01: "Target Zero is designed to amplify products and packaging that seek to eliminate single-use waste to landfill, promote the circulation of valuable materials through reuse and fill, and to showcase packaging innovation through new materials and formats that reduce waste to landfill.",
      description02: "Learn more about Target Zero",
      description03: "https://www.target.com/c/target-zero/-/N-hnosx",
    },
    {
      id: 3,
      key: "03",
      width: 1000,
      left: 40,
      top: 105,
      color: "#0891b2",
      image: Circular,
      label: "Circular By Design",
      description01: "As we develop and manufacture Target owned brand products, we are taking steps to eliminate waste, keep products and materials in use longer and decrease our dependency on natural resources, thereby strengthening our business",
      description02: "Learn more about Circularity at Target",
      description03: "https://corporate.target.com/sustainability-governance/circularity)",  
    },
  ],

  MOMENTS: [
    {
      id: 1,
      key: "01",
      width: 80,
      left: 40,
      top: 5,
      color: "#06b6d4",
      label: "Black History Month",
      description01: "Target Foward Moments (Storytelling):Black History Month",
      description02: "• Black Beyond Measure",
      description03: "• Black Farm Cotton",
    },
    {
      id: 2,
      key: "02",
      width: 80,
      left: 40,
      top: 55,
      color: "#06b6d4",
      label: "Spring Newness (Beauty)",
      description01: "Target Foward Moments (Storytelling): Spring Newness - Seasonal Merc Transition ",
      description02: "• Beauty + Target Clean story",
      description03: "",
    },
    {
      id: 3,
      key: "03",
      width: 80,
      left: 200,
      top: 5,
      color: "#06b6d4",
      label: "Earth Month",
      description01: "Target Foward Moments (Storytelling): Earth Month",
      description02: "• EON, Accelerating Circularity, Recycled Denim, Ciclo (Universal Thread)",
      description03: "• Sustainable Seafood, Waterless formulations (Kindfull)",
      description04: "• Palm, Seafood, etc.​ (Good & Gather)",
      description05: "• Sustainable Furniture (Home)",
      description06: "• Car Seat Trade-In (Brightroom & Sunsquad)",
      description07: "• Integration into Target Zero always on story",
    },
    {
      id: 4,
      key: "04",
      width: 80,
      left: 200,
      top: 55,
      color: "#06b6d4",
      label: "Spring Newness (Everyday Care)",
      description01: "Target Foward Moments (Storytelling): Spring Newness - Seasonal Merc Transition",
      description02: "• Everyday Care: Essentials & Healthcare",
      description03: "",
    },
    {
      id: 5,
      key: "05",
      width: 80,
      left: 455,
      top: 5,
      color: "#06b6d4",
      label: "Pride",
      description01: "Target Foward Moments (Storytelling): Pride Month",
      description02: "• Story/Brands TBD",
      description03: "",
    },
    {
      id: 6,
      key: "06",
      width: 170,
      left: 543,
      top: 5,
      color: "#06b6d4",
      label: "BTS/BTC Dressing",
      description01: "Target Foward Moments (Storytelling): BTS/BTC Dressing",
      description02: "• Better Denim (Universal Thread, Wild Fable, Cat & Jack, Goodfellow)",
      description03: "• Durability (Cat & Jack)",
    },
    {
      id: 7,
      key: "07",
      width: 170,
      left: 543,
      top: 55,
      color: "#06b6d4",
      label: "Innovation (Starbucks)",
      description01: "Target Foward Moments (Storytelling): Innovation",
      description02: "• Next Gen/Starbucks Reusable Cup Pilot",
      description03: "",
    },
    {
      id: 8,
      key: "08",
      width: 80,
      left: 965,
      top: 55,
      color: "#06b6d4",
      label: "Wellness",
      description01: "Target Foward Moments (Storytelling): Wellness",
      description02: "• E&B or F&B Transition story TBC",
      description03: "",
    },
  ],


  // ===================== STRATEGIC PARTNERSHIP

  DISNEY: [
    {
      id: 1,
      key: "01",
      width: 90,
      left: 290,
      top: 5,
      color: "#0369a1",
      label: "The Phantom Menace 25th",
      description01:
        "[Shop] The Phantom Menace: Celebrate the 25th Anniversary",
      description02: "• Set: TBC",
      description03: "• Pyramid: Hardlines (Toys)",
    },
    {
      id: 2,
      key: "02",
      width: 90,
      left: 625,
      top: 5,
      color: "#0369a1",
      label: "Nikkolas Smith x Marvel",
      description01: "[Shop] Nikkolas Smith x Marvel Collaboration",
      description02:
        "• Set: July W3 (7/21) - September",
      description03:
        "• Pyramid: A&A (Mens & Kids)",
    },
    {
      id: 3,
      key: "02",
      width: 90,
      left: 625,
      top: 55,
      color: "#0369a1",
      label: "Star Wars LEGO",
      description01: "[Shop] Star Wars LEGO: The Force That Connects us",
      description02: "• Set: TBC",
      description03: "• Pyramid: Hardlines (Toys)",
    },
    {
      id: 4,
      key: "02",
      width: 160,
      left: 800,
      top: 5,
      color: "#0369a1",
      label: "Toy Catalog",
      description01: "[Q4 Gifting] Disney/Toy Catalog",
      description02:"• Set: F24 Toys Transition 7/21",
      description03:"• Pyramid: Hardlines (Toys)",
    },
    {
      id: 5,
      key: "02",
      width: 90,
      left: 800,
      top: 55,
      color: "#0369a1",
      label: "Moana 2",
      description01: "[Explore] Disney/Toy Catalog",
      description02: "• Set: November",
      description03: "• Pyramid: Hardlines (Toys)",
    },
  ],

  APPLE: [
    {
      id: 1,
      key: "01",
      width: 160,
      left: 290,
      top: 5,
      color: "#0284c7",
      label: "Mom's/Dad's Day Tech Gifts",
      description01: "Mother's & Father's Day Gifts: Apple Tech ",
      description02:
        "• Product Categories: iPads & Watches",
      description03:
        "• Mother's Day: May 12",
      description04:
        "• Father's Day: June 16",
    },
    {
      id: 2,
      key: "02",
      width: 160,
      left: 455,
      top: 5,
      color: "#0284c7",
      label: "BTS/BTC Tech",
      description01: "BTS/BTC Apple Tech (Key Drive Time)",
      description02:
        "•  Product Categories: iPads, Accessories, AirPods (Macbook TBD)",
        description03:
          "• Set: TBC",
    },
    {
      id: 3,
      key: "03",
      width: 90,
      left: 705,
      top: 5,
      color: "#0284c7",
      label: "Tech Gifts (Q3)",
      description01: "Apple Tech Gifts (Q3) ",
      description02:
        "• Product Categories: iPad, Watches, AirPods, Accessories",
      description03:
        "• Set: TBC",
    },
    {
      id: 4,
      key: "04",
      width: 160,
      left: 795,
      top: 55,
      color: "#0284c7",
      label: "Tech Gifts (Q4)",
      description01: "Apple Tech Gifts (Q4) ",
      description02:
        "• Product Categories: iPad, Watches, AirPods, Accessories",
      description03:
        "• Set: TBC",
    },
    {
      id: 5,
      key: "02",
      width: 90,
      left: 960,
      top: 55,
      color: "#0284c7",
      label: "Wellbeing",
      description01: "Apple Wellbeing ",
      description02: "• Product Categories:  Watches, AirPods",
      description03: "• Set: TBC",
    },
  ],

  LEVI: [
    {
      id: 1,
      key: "01",
      width: 80,
      left: 37,
      top: 5,
      color: "#0ea5e9",
      label: "Spring Newness",
      description01:
        "",
      description02:
        "RTW Women's: Product Categories: Baggy Trends, Denim Dressing (Truckers, Vests, Jumpsuits/Rompers), Shorts",
      description03:
        "• Set: Feb Wk 2/3",
      description04:
        "• Men's Set Week: Product Categories: Classic Denim, Woven Shirts, Refreshed Fleece, Tees",
      description05:
        "• Set: Feb Wk 3/4",
    },
    {
      id: 2,
      key: "02",
      width: 80,
      left: 119,
      top: 5,
      color: "#0ea5e9",
      label: "RTW Easter",
      description01:
        "Levi's RTW Easter ",
      description02: "• Product Categories: Baggy Trends, Denim Dressing (Truckers, Vests, Jumpsuits/Rompers)",
      description03: "• Set: Mar Wk 3-Apr Wk 2",
    },
    {
      id: 3,
      key: "03",
      width: 170,
      left: 455,
      top: 5,
      color: "#0ea5e9",
      label: "RTW BTS/BTC",
      description01:
        "Levi's RTW BTS/BTC (Key Drive Time)",
      description02: "• Product Categories: Knit Exclusives - OPP $19.99 to 24.99/29.99 & Denim Dressing ",
      description03: "• Set: July Wk 4",
    },
    {
      id: 4,
      key: "04",
      width: 85,
      left: 455,
      top: 55,
      color: "#0ea5e9",
      label: "Men's Fall Newness",
      description01:
        "Levi's Men's Fall Newness   ",
      description02: "• Product Categories: New denim fits, 511 Tech pant, New LS knits + refreshed sportswear",
      description03: "• Set: July Wk 3/4",
    },
    {
      id: 5,
      key: "05",
      width: 165,
      left: 630,
      top: 55,
      color: "#0ea5e9",
      label: "RTW Fall Newness",
      description01:
        "Levi's RTW Fall Newness (Key Drive Time)",
      description02: "• Product Categories: Knit Exclusives - OPP $19.99 to 24.99/29.99",
      description03: "• Set: Sept Wk 4 - Oct Wk 2",
    },
    {
      id: 6,
      key: "06",
      width: 170,
      left: 800,
      top: 55,
      color: "#0ea5e9",
      label: "RTW Key Promo",
      description01: "Levi's RTW Key Promo ",
      description02: "• Product Categories: TBC",
      description03: "• Set:TBC",
    },
    {
      id: 7,
      key: "07",
      width: 170,
      left: 800,
      top: 105,
      color: "#0ea5e9",
      label: "Men's Holiday",
      description01: "Levi's Men's Holiday: Thanksgiving & Christmas",
      description02: "• Men's Thanksgiving: Set Nov W4-Dec W1",
      description03: "• Set:TBC",
    },
  ],

  ULTA: [
    {
      id: 1,
      key: "01",
      width: 170,
      left: 119,
      top: 5,
      color: "#38bdf8",
      label: "Ulta 21 Days of Beauty",
      description01:
        "Ulta 21 Days of Beauty (Q1 Event) ",
      description02:
        "• Details TBD",
    },
    {
      id: 2,
      key: "02",
      width: 85,
      left: 370,
      top: 55,
      color: "#38bdf8",
      label: "Kylie Cosmetics Launch",
      description01:
        "Product Categories: Cosmetics ",
      description02: "• Set: TBD",
    },
    {
      id: 3,
      key: "03",
      width: 170,
      left: 545,
      top: 5,
      color: "#38bdf8",
      label: "BTS/BTC Beauty",
      description01:
        "Product Categories: Skincare, Haircare, Cosmetics",
      description02: "• Focus: Affordability",
      description03: "• Set: TBD",
    },
    {
      id: 4,
      key: "04",
      width: 165,
      left: 630,
      top: 55,
      color: "#38bdf8",
      label: "Ulta 21 Days of Beauty",
      description01:
        "Ulta 21 Days of Beauty (Q3 Event) ",
      description02: "• Details TBD",
      description03: "",
    },
    {
      id: 5,
      key: "05",
      width: 160,
      left: 800,
      top: 55,
      color: "#38bdf8",
      label: "Beauty Gifts",
      description01:
        "Product Categories: All ",
      description02: "• Focus: Minis, Kits/Gift Sets",
      description03: "• Set: TBD",
    },
  ],


  NATIONAL: [
    {
      id: 1,
      key: "01",
      width: 80,
      left: 200,
      top: 5,
      color: "#7dd3fc",
      label: "Project Crown Pickleball",
      description01:
        "Product Categories: Sporting Goods, A&A",
      description02:
        "• Set: 4/21 (4-5 weeks)",
    },
    {
      id: 2,
      key: "02",
      width: 80,
      left: 455,
      top: 5,
      color: "#7dd3fc",
      label: "Project SZ",
      description01:
        "Product Categories: Apparel & Shoes",
      description02: "• Set: July Wk 2/3 (300 stores + digital)",
    },
    {
      id: 3,
      key: "03",
      width: 80,
      left: 630,
      top: 5,
      color: "#7dd3fc",
      label: "Project Charlie",
      description01:
        "Product Categories: Kids Apparel",
      description02: "• Set: Sept Wk 2 (100 stores + digital)",
      description03: "",
    },
  
  ],
};
